#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3.1'
services:
  api-full-rest:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-10
    container_name: backend-petshop_v2
    volumes:
      - ../../api-full-rest-pet-shop_v2:/workspace/api-full-rest-pet-shop_v2:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - petshop
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: database-petshop_v2
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=agenda-petshop_v2
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123456
    volumes:
      - ../../api-full-rest-pet-shop_v2/db:/workspace/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - petshop

networks:
  petshop:
    driver: bridge
